name: Project cicd flow
on:
  push:
  - "master"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 8.5.5

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod

     name: Build & push Docker image
     uses: mr-smithers-excellent/docker-build-push@v5
    with:
      image: neeleshkv/angular-istcosa-image
      tags: latest
      registry: docker.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}


        # uses: ncipollo/release-action@v3
        # with:
        #   artifacts: "dist/testing-docker/index.html*"
        #   token: ${{ secrets.TOKEN }}


        #   name: GitHub Pages

# - name: Build and push Docker images
  # uses: docker/build-push-action@v4.0.0









  # - uses: mr-smithers-excellent/docker-build-push@v5
  #   name: Build & push Docker image
  #   with:
  #     image: repo/image
  #     tags: v1, latest
  #     registry: registry-url.io
  #     dockerfile: Dockerfile.ci
  #     username: ${{ secrets.DOCKER_USERNAME }}
  #     password: ${{ secrets.DOCKER_PASSWORD }}



# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18

#     - name: Install dependencies
#       run: npm install

#     - name: Build
#       run: npm run build:prod
#     - name: Deploy
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: dist/angular-github-actions



